### ISSUE TITLE
Thread lock in LuaJIT when LuaDkmDebugger is attached

### ISSUE THREAD

**Issue by Xottab-DUTY** [WheretIB/LuaDkmDebugger#11] opened 2021-04-06 20:25 UTC
My case is
1. You need to have S.T.A.L.K.E.R.: Call of Pripyat or S.T.A.L.K.E.R.: Clear Sky.
2. Compile [OpenXRay project](https://github.com/OpenXRay/xray-16) from sources with Release x64 or Release Master Gold x64 configuration according to the [instructions](https://github.com/OpenXRay/xray-16/wiki/%5BEN%5D-How-to-build-and-setup-on-Windows).
3. Enable 'Attach on Launch' of LuaDkmDebugger.
4. Launch the game from the Visual Studio.
5. The main thread will freeze forever inside LuaJIT in `lua_newstate` function, on `if (!lj_prng_seed_secure(&prng)) {` line.
![image](https://user-images.githubusercontent.com/2989212/113773155-4e20e300-972e-11eb-9d90-888e4e9b91f2.png)

Probably, this can be reproduced with just dummy project that calls LuaJIT's implementation of `lua_newstate`, but I'm not sure.

This issue doesn't require LuaJIT support like #8 :) Just a possibility to improve the interaction with unknown Lua implementations.

**Comment by WheretIB** [comment] 2021-06-13 23:21
I couldn't reproduce the thread lock (thread suspend at this point is possible, but I only know of a case when debugging x64 Windows 10 UWP)
I didn't have resources to correctly run the OpenXRay project, but I could get it to a point where CScriptEngine::reinit is executed and thread didn't lock for me.

After looking at the debugger code I have found a case where debugger helper process launch can throw an exception and it wasn't handled correctly.
I have included a fix for that in a Beta release: https://github.com/WheretIB/LuaDkmDebugger/releases/tag/v0.9.7
If the fix helps, sadly it would mean that the helper process for breakpoint/stepping hooks will not be available and only limited call stack inspection will be available.

If you can enable Lua Debugger -> Enable Debug Logs and attach the log here, it might help identifying the issue.
Those logs can contain file paths, so look over them if you feel that they might contain private information (like source file names or the name of the PC User folder)

**Comment by Xottab-DUTY** [comment] 2021-06-14 13:39
It still did hang in the same place. (well, inside `lj_prng_seed_secure`)
![image](https://user-images.githubusercontent.com/2989212/121901182-d8895280-cd2e-11eb-8587-67c2d5eb9ef2.png)

**Comment by Xottab-DUTY** [comment] 2021-06-14 13:46
Where I can find the logs?

**Comment by WheretIB** [comment] 2021-06-14 13:57
Log should be next to the executable that is being debugged.
Delete the old file before the launch so that only the last debugger
session will be stored there.

**Comment by Xottab-DUTY** [comment] 2021-06-14 14:46
> Log should be next to the executable that is being debugged.

Yeah, I managed to find it immediately after I asked where I can find it :D

**Comment by WheretIB** [comment] 2021-06-15 08:27
Can you show the status line from the bottom of the 'Lua Script List' panel?
![image](https://user-images.githubusercontent.com/7524683/122012726-28ffbf00-cdc6-11eb-97e9-55a783001394.png)

**Comment by Xottab-DUTY** [comment] 2021-06-15 17:52
![image](https://user-images.githubusercontent.com/2989212/122100220-9b4ebe80-ce1b-11eb-8ed8-f92b287001a1.png)

**Comment by WheretIB** [comment] 2021-06-15 23:18
Thank you, I was able to identify and reproduce the problem.

**Comment by WheretIB** [comment] 2021-07-18 21:50
Fix for this issue has been released in https://github.com/WheretIB/LuaDkmDebugger/releases/tag/v0.9.8 and on the Markeplace.

**Closed by WheretIB** 2021-07-18 21:50 UTC
Labels: bug
